services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: pass_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
