version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: pass_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./blueberry:/var/www/html/themes/blueberry
    networks:
      - default

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: pass_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pass_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  postgres_data:
    driver: local
