version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: pass_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

volumes:
  mongodb_data:
    driver: local
