version: "3"
services:
  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db_mysql
    volumes:
      - ./blueberry:/var/www/html/themes/blueberry

  node-server:
    container_name: node
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - phpmyadmin

volumes:
  mysql_data_test:
    driver: local
